export const ILLUSTRATION_NAMES = [
  'artboard',
  'augmented-reality',
  'big-data',
  'chrenddrer',
  'comparison',
  'compas',
  'content',
  'data-analysis',
  'desk-lamp',
  'desktop-only',
  'developing',
  'dna',
  'drag-and-drop',
  'duplicate',
  'fault',
  'focus',
  'folder',
  'illustration',
  'labs',
  'loss',
  'map',
  'no-api',
  'nutrition',
  'out-of-stock',
  'paper-plane',
  'password',
  'plug',
  'relational',
  'report',
  'startup',
  'storytelling',
  'strategy',
  'success',
  'table',
  'text',
  'verification',
] as const;

export type IllustrationName = (typeof ILLUSTRATION_NAMES)[number];
