// `Config` from `/internal` rather than the `@stencil/core` re-export (`StencilConfig`):
// only the internal interface declares `buildDocs`, which the compiler reads at runtime.
import type { Config, OutputTarget } from '@stencil/core/internal';
import { angularOutputTarget as angular } from '@stencil/angular-output-target';
import { postcss } from '@stencil/postcss';
import { reactOutputTarget as react } from '@stencil/react-output-target';
import { vueOutputTarget as vue } from '@stencil/vue-output-target';

import { angularValueAccessorConfigs, vueComponentModels } from './scripts/adapters/form-models';
import { PROXY_DIRS } from './scripts/adapters/proxy-dirs';
import { stencilPostcssPlugins } from './stencil-postcss.config.mjs';
// import postcssPresetEnv from 'postcss-preset-env';

const args = process.argv.slice(2);
const isWatchMode = args.includes('--watch');
const isDevMode = args.includes('--dev');
// PERF: Source maps only for non-watch dev builds (dx:stencil:once).
// Watch mode skips them for faster incremental rebuilds.
const shouldGenerateSourceMaps = isDevMode && !isWatchMode;

const outputTargets: OutputTarget[] = [
  {
    type: 'dist',
    esmLoaderPath: '../loader',
    // PERF: In watch mode, Style Dictionary writes directly to tokens/generated/
    // and Storybook reads from there — no copy needed. Skip in watch to avoid a second
    // dist write that triggers an extra stencil-hot-reload cycle in Storybook.
    copy: isWatchMode
      ? []
      : [
          {
            src: '../tokens/generated/*.css',
            dest: 'tokens',
            warn: false,
          },
          {
            src: 'assets/fonts/*.woff2',
            dest: 'assets/fonts',
            warn: false,
          },
          {
            src: 'components/mud-phone-input/assets/flags/LICENSE',
            dest: 'licenses/flag-icons.txt',
            warn: true,
          },
        ],
  },
];

// Storybook builds every API table from this manifest (`.storybook/preview.js`).
// It is written by Stencil from the same decorators and `@part` tags as `readme.md`,
// so the tables and the readmes cannot disagree (issue #18).
outputTargets.push({
  type: 'docs-custom-elements-manifest',
  file: '.storybook/custom-elements.json',
});

// PERF: The base build only needs 'dist' (lazy). www output is unused —
// skip it entirely. docs-readme only on --docs.
const hasDocs = args.includes('--docs');
if (hasDocs) {
  outputTargets.push({ type: 'docs-readme' });
}

// The standalone custom-elements bundle is part of the published contract —
// `package.json` declares `exports["./components"]` unconditionally and
// `packages/react/src/index.ts` imports `setAssetPath` from it. It is therefore built
// for every non-dev build: what the package contains must not depend on which
// flag CI happened to pass.
//
// `!isDevMode` rather than unconditional, because `yarn dev` / `yarn start`
// rebuild in watch mode many times an hour and a second full component bundle
// per rebuild buys nothing there.
//
if (!isDevMode) {
  outputTargets.push({ type: 'dist-custom-elements', externalRuntime: false });
}

// The framework proxies are generated by the same non-dev build as the bundle they
// wrap, so no adapter build needs a second Stencil run. They are written into the
// adapter workspaces, not into the published package. Each `outDir` comes from
// `scripts/adapters/proxy-dirs.ts`, the one list that `clean-proxy-dirs.mjs` empties
// before the build and that the wireit `output`, the ignore files and the fixture
// runner's guard are checked against.
if (!isDevMode) {
  outputTargets.push(
    react({
      outDir: PROXY_DIRS.react,
      esModules: true,
      stencilPackageName: '@egov-moldova/mud',
      // The physical output stays `dist/components/`; this names the segment the
      // generated wrappers put in their import specifiers, which must match the
      // `./components/mud-*.js` key in package.json rather than the build
      // directory. `scripts/__tests__/validate-package.spec.mjs` asserts the two
      // agree — nothing else does, and the only other detector is `tsc --noEmit`
      // in a workspace whose build script is `tsc || true`.
      //
      // Setting it also takes the early-return branch of react-output-target's
      // own `validate()`, which otherwise asserts that a `dist-custom-elements`
      // target exists AND that its `externalRuntime` is false. Removing
      // `externalRuntime: false` above would therefore no longer fail the build;
      // the wrappers would generate against an external runtime and break at
      // runtime instead. Keep the two together.
      customElementsDir: 'components',
      excludeComponents: [],
    }),
    // Vue: the standalone bundle only, with `esModules` set explicitly (the target's code checks
    // `=== true`). The generated wrappers import `@egov-moldova/mud/components/mud-*.js`, so the
    // `customElementsDir` pairing above applies here too. `componentModels` is derived from the
    // form-control model map, the one list the Angular accessors derive from as well, and which
    // `scripts/__tests__/adapter-form-models.spec.mjs` checks against the component manifest.
    // It lists only the rows the generator can bind (one event, no numeric value): the others
    // (numeric, phone) are hand-written in packages/vue/src/wrappers/ and replace the generated
    // wrappers of the same name in the package's exports.
    vue({
      componentCorePackage: '@egov-moldova/mud',
      proxiesFile: `${PROXY_DIRS.vue}/components.ts`,
      includeImportCustomElements: true,
      esModules: true,
      customElementsDir: 'components',
      componentModels: vueComponentModels(),
    }),
    // Angular: standalone components over the same standalone bundle (`esModules` set explicitly,
    // as for Vue: the target's code checks `=== true`). `inlineProperties` is REQUIRED, not a
    // nicety: without it the wrappers declare no typed inputs, so `strictTemplates` checks no
    // binding and `booleanAttributes`' transform has nothing to resolve. The library compiles the
    // `@egov-moldova/mud/components/mud-*.js` imports through the `exports` map with
    // `moduleResolution: bundler` (packages/angular/tsconfig.json), so no shim folder exists.
    // `valueAccessorConfigs` is derived from the form-control model map, grouped into one config
    // per (type, event, property); the rows the generator cannot serve (numeric, chips, files)
    // get the hand-written accessors in packages/angular/src/lib/accessors/.
    //
    // DEBT(angular-wrapper-side-effects): every generated wrapper defines its element when its
    // class loads (`@ProxyCmp({ defineCustomElementFn })`), so the package cannot declare
    // `"sideEffects": false` and an Angular bundle includes ALL wrappers, whichever the app
    // imports. The honest version is wrappers that define their element on first use, so a
    // bundler can drop the ones an app never imports.
    angular({
      componentCorePackage: '@egov-moldova/mud',
      directivesProxyFile: `${PROXY_DIRS.angular}/components.ts`,
      outputType: 'standalone',
      esModules: true,
      customElementsDir: 'components',
      booleanAttributes: true,
      inlineProperties: true,
      valueAccessorConfigs: angularValueAccessorConfigs(),
    }),
  );
}

export const config: Config = {
  namespace: 'mud',
  srcDir: 'src',
  // Stencil compiles only `src`. The root-level `*.ts` files that
  // `tsconfig.json` includes for `yarn typecheck` (stencil.config.ts,
  // playwright.config.ts, vitest-setup.ts) must stay out of the emitted
  // program: they were being written to `dist/*.js`, and their declarations
  // landed under an absolute build-machine path in `dist/types/`.
  tsconfig: 'tsconfig.stencil.json',
  globalStyle: 'src/assets/css/index.css',
  sourceMap: shouldGenerateSourceMaps,
  // PERF: Always enable cache — allows incremental rebuilds in watch mode.
  enableCache: true,
  // PERF: Stable filenames in watch mode — no content-hash churn means Vite
  // module graph stays valid between rebuilds (fewer modules need invalidating).
  hashFileNames: !isWatchMode,
  outputTargets,
  // Docs output targets only run when this is true, and Stencil defaults it to false
  // under `--dev`. Forced on so the watch build behind `yarn dev` keeps the Storybook
  // manifest current. `docs-readme` is still added only under `--docs`, so dev builds
  // write no readme files. Measured on a one-shot `stencil build --dev` (3 runs each):
  // 7.27 s without the manifest target, 7.19 s with it; watch rebuilds were not timed.
  buildDocs: true,
  // Testing is now handled by Vitest via @stencil/vitest.
  // See vitest.config.ts + vitest-setup.ts.
  extras: {
    // Enable import injection for Vite/Storybook static build compatibility
    enableImportInjection: true,
  },
  plugins: [
    postcss({
      plugins: stencilPostcssPlugins(),
    }),
  ],
};
