// @ts-nocheck
'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import {
  type BreadcrumbItemClickEvent,
  type BreadcrumbsEllipsisItemClickEvent,
  type CorAccordionCustomEvent,
  type CorAccordionToggleEventDetail,
  type CorBadgeInteractiveCustomEvent,
  type CorBannerNotificationCustomEvent,
  type CorBreadcrumbsCustomEvent,
  type CorBreadcrumbsEllipsisCustomEvent,
  type CorCalendarCustomEvent,
  type CorCheckboxCustomEvent,
  type CorCheckboxGroupCustomEvent,
  type CorChipClickEventDetail,
  type CorChipCustomEvent,
  type CorColumnActionCustomEvent,
  type CorDatepickerCustomEvent,
  type CorDatepickerDayCustomEvent,
  type CorInlineNotificationCustomEvent,
  type CorInputCustomEvent,
  type CorMenuButtonCustomEvent,
  type CorModalCustomEvent,
  type CorPaginationCustomEvent,
  type CorPaginationGoToCustomEvent,
  type CorPaginationItemCustomEvent,
  type CorPaginationPageSizeCustomEvent,
  type CorRadioButtonCustomEvent,
  type CorRadioButtonGroupCustomEvent,
  type CorRejectedFile,
  type CorRowCustomEvent,
  type CorSelectCustomEvent,
  type CorSelectItemCustomEvent,
  type CorSortingCustomEvent,
  type CorTabButtonCustomEvent,
  type CorTabsCustomEvent,
  type CorTextareaCustomEvent,
  type CorTheadCustomEvent,
  type CorTimelineChangeEvent,
  type CorTimelineCustomEvent,
  type CorTimelineScrollEndEvent,
  type CorToastNotificationCustomEvent,
  type CorToggleCustomEvent,
  type CorTooltipCustomEvent,
  type CorUploadAreaCustomEvent,
  type CorUploadFile,
  type CorUploadFileItemCustomEvent,
  type DateChangePayload,
  type DatepickerChangePayload,
  type DatepickerRangeChangePayload,
  type MonthChangePayload,
  type RangeChangePayload,
} from '@age/design-system';
import type { Components } from '@age/design-system/dist/components';
import {
  CorAccordion as CorAccordionElement,
  defineCustomElement as defineCorAccordion,
} from '@age/design-system/dist/components/cor-accordion.js';
import {
  CorAvatarGroup as CorAvatarGroupElement,
  defineCustomElement as defineCorAvatarGroup,
} from '@age/design-system/dist/components/cor-avatar-group.js';
import {
  CorAvatar as CorAvatarElement,
  defineCustomElement as defineCorAvatar,
} from '@age/design-system/dist/components/cor-avatar.js';
import {
  CorBadgeInteractive as CorBadgeInteractiveElement,
  defineCustomElement as defineCorBadgeInteractive,
} from '@age/design-system/dist/components/cor-badge-interactive.js';
import {
  CorBadge as CorBadgeElement,
  defineCustomElement as defineCorBadge,
} from '@age/design-system/dist/components/cor-badge.js';
import {
  CorBannerNotification as CorBannerNotificationElement,
  defineCustomElement as defineCorBannerNotification,
} from '@age/design-system/dist/components/cor-banner-notification.js';
import {
  CorBreadcrumbsEllipsis as CorBreadcrumbsEllipsisElement,
  defineCustomElement as defineCorBreadcrumbsEllipsis,
} from '@age/design-system/dist/components/cor-breadcrumbs-ellipsis.js';
import {
  CorBreadcrumbs as CorBreadcrumbsElement,
  defineCustomElement as defineCorBreadcrumbs,
} from '@age/design-system/dist/components/cor-breadcrumbs.js';
import {
  CorButton as CorButtonElement,
  defineCustomElement as defineCorButton,
} from '@age/design-system/dist/components/cor-button.js';
import {
  CorCalendar as CorCalendarElement,
  defineCustomElement as defineCorCalendar,
} from '@age/design-system/dist/components/cor-calendar.js';
import {
  CorCell as CorCellElement,
  defineCustomElement as defineCorCell,
} from '@age/design-system/dist/components/cor-cell.js';
import {
  CorCheckboxGroup as CorCheckboxGroupElement,
  defineCustomElement as defineCorCheckboxGroup,
} from '@age/design-system/dist/components/cor-checkbox-group.js';
import {
  CorCheckbox as CorCheckboxElement,
  defineCustomElement as defineCorCheckbox,
} from '@age/design-system/dist/components/cor-checkbox.js';
import {
  CorChip as CorChipElement,
  defineCustomElement as defineCorChip,
} from '@age/design-system/dist/components/cor-chip.js';
import {
  CorColumnAction as CorColumnActionElement,
  defineCustomElement as defineCorColumnAction,
} from '@age/design-system/dist/components/cor-column-action.js';
import {
  CorColumn as CorColumnElement,
  defineCustomElement as defineCorColumn,
} from '@age/design-system/dist/components/cor-column.js';
import {
  CorDatepickerDay as CorDatepickerDayElement,
  defineCustomElement as defineCorDatepickerDay,
} from '@age/design-system/dist/components/cor-datepicker-day.js';
import {
  CorDatepicker as CorDatepickerElement,
  defineCustomElement as defineCorDatepicker,
} from '@age/design-system/dist/components/cor-datepicker.js';
import {
  CorGrid as CorGridElement,
  defineCustomElement as defineCorGrid,
} from '@age/design-system/dist/components/cor-grid.js';
import {
  CorIcon as CorIconElement,
  defineCustomElement as defineCorIcon,
} from '@age/design-system/dist/components/cor-icon.js';
import {
  CorIllustration as CorIllustrationElement,
  defineCustomElement as defineCorIllustration,
} from '@age/design-system/dist/components/cor-illustration.js';
import {
  CorInlineNotification as CorInlineNotificationElement,
  defineCustomElement as defineCorInlineNotification,
} from '@age/design-system/dist/components/cor-inline-notification.js';
import {
  CorInput as CorInputElement,
  defineCustomElement as defineCorInput,
} from '@age/design-system/dist/components/cor-input.js';
import {
  CorLabel as CorLabelElement,
  defineCustomElement as defineCorLabel,
} from '@age/design-system/dist/components/cor-label.js';
import {
  CorLink as CorLinkElement,
  defineCustomElement as defineCorLink,
} from '@age/design-system/dist/components/cor-link.js';
import {
  CorLoadingDots as CorLoadingDotsElement,
  defineCustomElement as defineCorLoadingDots,
} from '@age/design-system/dist/components/cor-loading-dots.js';
import {
  CorLoadingPercentage as CorLoadingPercentageElement,
  defineCustomElement as defineCorLoadingPercentage,
} from '@age/design-system/dist/components/cor-loading-percentage.js';
import {
  CorLoading as CorLoadingElement,
  defineCustomElement as defineCorLoading,
} from '@age/design-system/dist/components/cor-loading.js';
import {
  CorMenuButton as CorMenuButtonElement,
  defineCustomElement as defineCorMenuButton,
} from '@age/design-system/dist/components/cor-menu-button.js';
import {
  CorModal as CorModalElement,
  defineCustomElement as defineCorModal,
} from '@age/design-system/dist/components/cor-modal.js';
import {
  CorPaginationGoTo as CorPaginationGoToElement,
  defineCustomElement as defineCorPaginationGoTo,
} from '@age/design-system/dist/components/cor-pagination-go-to.js';
import {
  CorPaginationItem as CorPaginationItemElement,
  defineCustomElement as defineCorPaginationItem,
} from '@age/design-system/dist/components/cor-pagination-item.js';
import {
  CorPaginationPageSize as CorPaginationPageSizeElement,
  defineCustomElement as defineCorPaginationPageSize,
} from '@age/design-system/dist/components/cor-pagination-page-size.js';
import {
  CorPagination as CorPaginationElement,
  defineCustomElement as defineCorPagination,
} from '@age/design-system/dist/components/cor-pagination.js';
import {
  CorProgressBar as CorProgressBarElement,
  defineCustomElement as defineCorProgressBar,
} from '@age/design-system/dist/components/cor-progress-bar.js';
import {
  CorRadioButtonGroup as CorRadioButtonGroupElement,
  defineCustomElement as defineCorRadioButtonGroup,
} from '@age/design-system/dist/components/cor-radio-button-group.js';
import {
  CorRadioButton as CorRadioButtonElement,
  defineCustomElement as defineCorRadioButton,
} from '@age/design-system/dist/components/cor-radio-button.js';
import {
  CorRow as CorRowElement,
  defineCustomElement as defineCorRow,
} from '@age/design-system/dist/components/cor-row.js';
import {
  CorScrollbar as CorScrollbarElement,
  defineCustomElement as defineCorScrollbar,
} from '@age/design-system/dist/components/cor-scrollbar.js';
import {
  CorSelectItem as CorSelectItemElement,
  defineCustomElement as defineCorSelectItem,
} from '@age/design-system/dist/components/cor-select-item.js';
import {
  CorSelect as CorSelectElement,
  defineCustomElement as defineCorSelect,
} from '@age/design-system/dist/components/cor-select.js';
import {
  CorSeparator as CorSeparatorElement,
  defineCustomElement as defineCorSeparator,
} from '@age/design-system/dist/components/cor-separator.js';
import {
  CorSkeleton as CorSkeletonElement,
  defineCustomElement as defineCorSkeleton,
} from '@age/design-system/dist/components/cor-skeleton.js';
import {
  CorSlot as CorSlotElement,
  defineCustomElement as defineCorSlot,
} from '@age/design-system/dist/components/cor-slot.js';
import {
  CorSorting as CorSortingElement,
  defineCustomElement as defineCorSorting,
} from '@age/design-system/dist/components/cor-sorting.js';
import {
  CorSpinner as CorSpinnerElement,
  defineCustomElement as defineCorSpinner,
} from '@age/design-system/dist/components/cor-spinner.js';
import {
  CorSystemMessage as CorSystemMessageElement,
  defineCustomElement as defineCorSystemMessage,
} from '@age/design-system/dist/components/cor-system-message.js';
import {
  CorTabButton as CorTabButtonElement,
  defineCustomElement as defineCorTabButton,
} from '@age/design-system/dist/components/cor-tab-button.js';
import {
  CorTableHeader as CorTableHeaderElement,
  defineCustomElement as defineCorTableHeader,
} from '@age/design-system/dist/components/cor-table-header.js';
import {
  CorTable as CorTableElement,
  defineCustomElement as defineCorTable,
} from '@age/design-system/dist/components/cor-table.js';
import {
  CorTabs as CorTabsElement,
  defineCustomElement as defineCorTabs,
} from '@age/design-system/dist/components/cor-tabs.js';
import {
  CorTbody as CorTbodyElement,
  defineCustomElement as defineCorTbody,
} from '@age/design-system/dist/components/cor-tbody.js';
import {
  CorTextarea as CorTextareaElement,
  defineCustomElement as defineCorTextarea,
} from '@age/design-system/dist/components/cor-textarea.js';
import {
  CorTfoot as CorTfootElement,
  defineCustomElement as defineCorTfoot,
} from '@age/design-system/dist/components/cor-tfoot.js';
import {
  CorThead as CorTheadElement,
  defineCustomElement as defineCorThead,
} from '@age/design-system/dist/components/cor-thead.js';
import {
  CorTimeline as CorTimelineElement,
  defineCustomElement as defineCorTimeline,
} from '@age/design-system/dist/components/cor-timeline.js';
import {
  CorToastNotification as CorToastNotificationElement,
  defineCustomElement as defineCorToastNotification,
} from '@age/design-system/dist/components/cor-toast-notification.js';
import {
  CorToggle as CorToggleElement,
  defineCustomElement as defineCorToggle,
} from '@age/design-system/dist/components/cor-toggle.js';
import {
  CorTooltip as CorTooltipElement,
  defineCustomElement as defineCorTooltip,
} from '@age/design-system/dist/components/cor-tooltip.js';
import {
  CorTypography as CorTypographyElement,
  defineCustomElement as defineCorTypography,
} from '@age/design-system/dist/components/cor-typography.js';
import {
  CorUploadArea as CorUploadAreaElement,
  defineCustomElement as defineCorUploadArea,
} from '@age/design-system/dist/components/cor-upload-area.js';
import {
  CorUploadFileItem as CorUploadFileItemElement,
  defineCustomElement as defineCorUploadFileItem,
} from '@age/design-system/dist/components/cor-upload-file-item.js';

export type CorAccordionEvents = {
  onCorAccordionToggle: EventName<CorAccordionCustomEvent<CorAccordionToggleEventDetail>>;
};

export const CorAccordion: StencilReactComponent<CorAccordionElement, CorAccordionEvents, Components.CorAccordion> =
  /*@__PURE__*/ createComponent<CorAccordionElement, CorAccordionEvents, Components.CorAccordion>({
    tagName: 'cor-accordion',
    elementClass: CorAccordionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorAccordionToggle: 'corAccordionToggle' } as CorAccordionEvents,
    defineCustomElement: defineCorAccordion,
  });

export type CorAvatarEvents = NonNullable<unknown>;

export const CorAvatar: StencilReactComponent<CorAvatarElement, CorAvatarEvents, Components.CorAvatar> =
  /*@__PURE__*/ createComponent<CorAvatarElement, CorAvatarEvents, Components.CorAvatar>({
    tagName: 'cor-avatar',
    elementClass: CorAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorAvatarEvents,
    defineCustomElement: defineCorAvatar,
  });

export type CorAvatarGroupEvents = NonNullable<unknown>;

export const CorAvatarGroup: StencilReactComponent<
  CorAvatarGroupElement,
  CorAvatarGroupEvents,
  Components.CorAvatarGroup
> = /*@__PURE__*/ createComponent<CorAvatarGroupElement, CorAvatarGroupEvents, Components.CorAvatarGroup>({
  tagName: 'cor-avatar-group',
  elementClass: CorAvatarGroupElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {} as CorAvatarGroupEvents,
  defineCustomElement: defineCorAvatarGroup,
});

export type CorBadgeEvents = NonNullable<unknown>;

export const CorBadge: StencilReactComponent<CorBadgeElement, CorBadgeEvents, Components.CorBadge> =
  /*@__PURE__*/ createComponent<CorBadgeElement, CorBadgeEvents, Components.CorBadge>({
    tagName: 'cor-badge',
    elementClass: CorBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorBadgeEvents,
    defineCustomElement: defineCorBadge,
  });

export type CorBadgeInteractiveEvents = { onCorClick: EventName<CorBadgeInteractiveCustomEvent<void>> };

export const CorBadgeInteractive: StencilReactComponent<
  CorBadgeInteractiveElement,
  CorBadgeInteractiveEvents,
  Components.CorBadgeInteractive
> = /*@__PURE__*/ createComponent<
  CorBadgeInteractiveElement,
  CorBadgeInteractiveEvents,
  Components.CorBadgeInteractive
>({
  tagName: 'cor-badge-interactive',
  elementClass: CorBadgeInteractiveElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorClick: 'corClick' } as CorBadgeInteractiveEvents,
  defineCustomElement: defineCorBadgeInteractive,
});

export type CorBannerNotificationEvents = { onCorDismiss: EventName<CorBannerNotificationCustomEvent<void>> };

export const CorBannerNotification: StencilReactComponent<
  CorBannerNotificationElement,
  CorBannerNotificationEvents,
  Components.CorBannerNotification
> = /*@__PURE__*/ createComponent<
  CorBannerNotificationElement,
  CorBannerNotificationEvents,
  Components.CorBannerNotification
>({
  tagName: 'cor-banner-notification',
  elementClass: CorBannerNotificationElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorDismiss: 'corDismiss' } as CorBannerNotificationEvents,
  defineCustomElement: defineCorBannerNotification,
});

export type CorBreadcrumbsEvents = {
  onCorBreadcrumbItemClick: EventName<CorBreadcrumbsCustomEvent<BreadcrumbItemClickEvent>>;
};

export const CorBreadcrumbs: StencilReactComponent<
  CorBreadcrumbsElement,
  CorBreadcrumbsEvents,
  Components.CorBreadcrumbs
> = /*@__PURE__*/ createComponent<CorBreadcrumbsElement, CorBreadcrumbsEvents, Components.CorBreadcrumbs>({
  tagName: 'cor-breadcrumbs',
  elementClass: CorBreadcrumbsElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorBreadcrumbItemClick: 'corBreadcrumbItemClick' } as CorBreadcrumbsEvents,
  defineCustomElement: defineCorBreadcrumbs,
});

export type CorBreadcrumbsEllipsisEvents = {
  onCorEllipsisItemClick: EventName<CorBreadcrumbsEllipsisCustomEvent<BreadcrumbsEllipsisItemClickEvent>>;
  onCorEllipsisOpen: EventName<CorBreadcrumbsEllipsisCustomEvent<void>>;
  onCorEllipsisClose: EventName<CorBreadcrumbsEllipsisCustomEvent<void>>;
};

export const CorBreadcrumbsEllipsis: StencilReactComponent<
  CorBreadcrumbsEllipsisElement,
  CorBreadcrumbsEllipsisEvents,
  Components.CorBreadcrumbsEllipsis
> = /*@__PURE__*/ createComponent<
  CorBreadcrumbsEllipsisElement,
  CorBreadcrumbsEllipsisEvents,
  Components.CorBreadcrumbsEllipsis
>({
  tagName: 'cor-breadcrumbs-ellipsis',
  elementClass: CorBreadcrumbsEllipsisElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {
    onCorEllipsisItemClick: 'corEllipsisItemClick',
    onCorEllipsisOpen: 'corEllipsisOpen',
    onCorEllipsisClose: 'corEllipsisClose',
  } as CorBreadcrumbsEllipsisEvents,
  defineCustomElement: defineCorBreadcrumbsEllipsis,
});

export type CorButtonEvents = NonNullable<unknown>;

export const CorButton: StencilReactComponent<CorButtonElement, CorButtonEvents, Components.CorButton> =
  /*@__PURE__*/ createComponent<CorButtonElement, CorButtonEvents, Components.CorButton>({
    tagName: 'cor-button',
    elementClass: CorButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorButtonEvents,
    defineCustomElement: defineCorButton,
  });

export type CorCalendarEvents = {
  onCorDateChange: EventName<CorCalendarCustomEvent<DateChangePayload>>;
  onCorRangeChange: EventName<CorCalendarCustomEvent<RangeChangePayload>>;
  onCorMonthChange: EventName<CorCalendarCustomEvent<MonthChangePayload>>;
};

export const CorCalendar: StencilReactComponent<CorCalendarElement, CorCalendarEvents, Components.CorCalendar> =
  /*@__PURE__*/ createComponent<CorCalendarElement, CorCalendarEvents, Components.CorCalendar>({
    tagName: 'cor-calendar',
    elementClass: CorCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorDateChange: 'corDateChange',
      onCorRangeChange: 'corRangeChange',
      onCorMonthChange: 'corMonthChange',
    } as CorCalendarEvents,
    defineCustomElement: defineCorCalendar,
  });

export type CorCellEvents = NonNullable<unknown>;

export const CorCell: StencilReactComponent<CorCellElement, CorCellEvents, Components.CorCell> =
  /*@__PURE__*/ createComponent<CorCellElement, CorCellEvents, Components.CorCell>({
    tagName: 'cor-cell',
    elementClass: CorCellElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorCellEvents,
    defineCustomElement: defineCorCell,
  });

export type CorCheckboxEvents = { onCorChange: EventName<CorCheckboxCustomEvent<boolean>> };

export const CorCheckbox: StencilReactComponent<CorCheckboxElement, CorCheckboxEvents, Components.CorCheckbox> =
  /*@__PURE__*/ createComponent<CorCheckboxElement, CorCheckboxEvents, Components.CorCheckbox>({
    tagName: 'cor-checkbox',
    elementClass: CorCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorChange: 'corChange' } as CorCheckboxEvents,
    defineCustomElement: defineCorCheckbox,
  });

export type CorCheckboxGroupEvents = { onCorChange: EventName<CorCheckboxGroupCustomEvent<string[]>> };

export const CorCheckboxGroup: StencilReactComponent<
  CorCheckboxGroupElement,
  CorCheckboxGroupEvents,
  Components.CorCheckboxGroup
> = /*@__PURE__*/ createComponent<CorCheckboxGroupElement, CorCheckboxGroupEvents, Components.CorCheckboxGroup>({
  tagName: 'cor-checkbox-group',
  elementClass: CorCheckboxGroupElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorChange: 'corChange' } as CorCheckboxGroupEvents,
  defineCustomElement: defineCorCheckboxGroup,
});

export type CorChipEvents = { onCorChipClick: EventName<CorChipCustomEvent<CorChipClickEventDetail>> };

export const CorChip: StencilReactComponent<CorChipElement, CorChipEvents, Components.CorChip> =
  /*@__PURE__*/ createComponent<CorChipElement, CorChipEvents, Components.CorChip>({
    tagName: 'cor-chip',
    elementClass: CorChipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorChipClick: 'corChipClick' } as CorChipEvents,
    defineCustomElement: defineCorChip,
  });

export type CorColumnEvents = NonNullable<unknown>;

export const CorColumn: StencilReactComponent<CorColumnElement, CorColumnEvents, Components.CorColumn> =
  /*@__PURE__*/ createComponent<CorColumnElement, CorColumnEvents, Components.CorColumn>({
    tagName: 'cor-column',
    elementClass: CorColumnElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorColumnEvents,
    defineCustomElement: defineCorColumn,
  });

export type CorColumnActionEvents = {
  onCorAction: EventName<CorColumnActionCustomEvent<MouseEvent>>;
  onCorActionBlur: EventName<CorColumnActionCustomEvent<void>>;
};

export const CorColumnAction: StencilReactComponent<
  CorColumnActionElement,
  CorColumnActionEvents,
  Components.CorColumnAction
> = /*@__PURE__*/ createComponent<CorColumnActionElement, CorColumnActionEvents, Components.CorColumnAction>({
  tagName: 'cor-column-action',
  elementClass: CorColumnActionElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {
    onCorAction: 'corAction',
    onCorActionBlur: 'corActionBlur',
  } as CorColumnActionEvents,
  defineCustomElement: defineCorColumnAction,
});

export type CorDatepickerEvents = {
  onCorChange: EventName<CorDatepickerCustomEvent<DatepickerChangePayload>>;
  onCorRangeChange: EventName<CorDatepickerCustomEvent<DatepickerRangeChangePayload>>;
  onCorBlur: EventName<CorDatepickerCustomEvent<void>>;
  onCorFocus: EventName<CorDatepickerCustomEvent<void>>;
};

export const CorDatepicker: StencilReactComponent<CorDatepickerElement, CorDatepickerEvents, Components.CorDatepicker> =
  /*@__PURE__*/ createComponent<CorDatepickerElement, CorDatepickerEvents, Components.CorDatepicker>({
    tagName: 'cor-datepicker',
    elementClass: CorDatepickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorChange: 'corChange',
      onCorRangeChange: 'corRangeChange',
      onCorBlur: 'corBlur',
      onCorFocus: 'corFocus',
    } as CorDatepickerEvents,
    defineCustomElement: defineCorDatepicker,
  });

export type CorDatepickerDayEvents = {
  onCorDayClick: EventName<CorDatepickerDayCustomEvent<{ date: string; day: number }>>;
  onCorDayFocus: EventName<CorDatepickerDayCustomEvent<{ date: string; day: number }>>;
  onCorDayHover: EventName<CorDatepickerDayCustomEvent<{ date: string; active: boolean }>>;
};

export const CorDatepickerDay: StencilReactComponent<
  CorDatepickerDayElement,
  CorDatepickerDayEvents,
  Components.CorDatepickerDay
> = /*@__PURE__*/ createComponent<CorDatepickerDayElement, CorDatepickerDayEvents, Components.CorDatepickerDay>({
  tagName: 'cor-datepicker-day',
  elementClass: CorDatepickerDayElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {
    onCorDayClick: 'corDayClick',
    onCorDayFocus: 'corDayFocus',
    onCorDayHover: 'corDayHover',
  } as CorDatepickerDayEvents,
  defineCustomElement: defineCorDatepickerDay,
});

export type CorGridEvents = NonNullable<unknown>;

export const CorGrid: StencilReactComponent<CorGridElement, CorGridEvents, Components.CorGrid> =
  /*@__PURE__*/ createComponent<CorGridElement, CorGridEvents, Components.CorGrid>({
    tagName: 'cor-grid',
    elementClass: CorGridElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorGridEvents,
    defineCustomElement: defineCorGrid,
  });

export type CorIconEvents = NonNullable<unknown>;

export const CorIcon: StencilReactComponent<CorIconElement, CorIconEvents, Components.CorIcon> =
  /*@__PURE__*/ createComponent<CorIconElement, CorIconEvents, Components.CorIcon>({
    tagName: 'cor-icon',
    elementClass: CorIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorIconEvents,
    defineCustomElement: defineCorIcon,
  });

export type CorIllustrationEvents = NonNullable<unknown>;

export const CorIllustration: StencilReactComponent<
  CorIllustrationElement,
  CorIllustrationEvents,
  Components.CorIllustration
> = /*@__PURE__*/ createComponent<CorIllustrationElement, CorIllustrationEvents, Components.CorIllustration>({
  tagName: 'cor-illustration',
  elementClass: CorIllustrationElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {} as CorIllustrationEvents,
  defineCustomElement: defineCorIllustration,
});

export type CorInlineNotificationEvents = { onCorDismiss: EventName<CorInlineNotificationCustomEvent<void>> };

export const CorInlineNotification: StencilReactComponent<
  CorInlineNotificationElement,
  CorInlineNotificationEvents,
  Components.CorInlineNotification
> = /*@__PURE__*/ createComponent<
  CorInlineNotificationElement,
  CorInlineNotificationEvents,
  Components.CorInlineNotification
>({
  tagName: 'cor-inline-notification',
  elementClass: CorInlineNotificationElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorDismiss: 'corDismiss' } as CorInlineNotificationEvents,
  defineCustomElement: defineCorInlineNotification,
});

export type CorInputEvents = {
  onCorInput: EventName<CorInputCustomEvent<string>>;
  onCorBlur: EventName<CorInputCustomEvent<void>>;
  onCorFocus: EventName<CorInputCustomEvent<void>>;
};

export const CorInput: StencilReactComponent<CorInputElement, CorInputEvents, Components.CorInput> =
  /*@__PURE__*/ createComponent<CorInputElement, CorInputEvents, Components.CorInput>({
    tagName: 'cor-input',
    elementClass: CorInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorInput: 'corInput',
      onCorBlur: 'corBlur',
      onCorFocus: 'corFocus',
    } as CorInputEvents,
    defineCustomElement: defineCorInput,
  });

export type CorLabelEvents = NonNullable<unknown>;

export const CorLabel: StencilReactComponent<CorLabelElement, CorLabelEvents, Components.CorLabel> =
  /*@__PURE__*/ createComponent<CorLabelElement, CorLabelEvents, Components.CorLabel>({
    tagName: 'cor-label',
    elementClass: CorLabelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorLabelEvents,
    defineCustomElement: defineCorLabel,
  });

export type CorLinkEvents = NonNullable<unknown>;

export const CorLink: StencilReactComponent<CorLinkElement, CorLinkEvents, Components.CorLink> =
  /*@__PURE__*/ createComponent<CorLinkElement, CorLinkEvents, Components.CorLink>({
    tagName: 'cor-link',
    elementClass: CorLinkElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorLinkEvents,
    defineCustomElement: defineCorLink,
  });

export type CorLoadingEvents = NonNullable<unknown>;

export const CorLoading: StencilReactComponent<CorLoadingElement, CorLoadingEvents, Components.CorLoading> =
  /*@__PURE__*/ createComponent<CorLoadingElement, CorLoadingEvents, Components.CorLoading>({
    tagName: 'cor-loading',
    elementClass: CorLoadingElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorLoadingEvents,
    defineCustomElement: defineCorLoading,
  });

export type CorLoadingDotsEvents = NonNullable<unknown>;

export const CorLoadingDots: StencilReactComponent<
  CorLoadingDotsElement,
  CorLoadingDotsEvents,
  Components.CorLoadingDots
> = /*@__PURE__*/ createComponent<CorLoadingDotsElement, CorLoadingDotsEvents, Components.CorLoadingDots>({
  tagName: 'cor-loading-dots',
  elementClass: CorLoadingDotsElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {} as CorLoadingDotsEvents,
  defineCustomElement: defineCorLoadingDots,
});

export type CorLoadingPercentageEvents = NonNullable<unknown>;

export const CorLoadingPercentage: StencilReactComponent<
  CorLoadingPercentageElement,
  CorLoadingPercentageEvents,
  Components.CorLoadingPercentage
> = /*@__PURE__*/ createComponent<
  CorLoadingPercentageElement,
  CorLoadingPercentageEvents,
  Components.CorLoadingPercentage
>({
  tagName: 'cor-loading-percentage',
  elementClass: CorLoadingPercentageElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {} as CorLoadingPercentageEvents,
  defineCustomElement: defineCorLoadingPercentage,
});

export type CorMenuButtonEvents = { onCorMenuSelect: EventName<CorMenuButtonCustomEvent<{ value: string }>> };

export const CorMenuButton: StencilReactComponent<CorMenuButtonElement, CorMenuButtonEvents, Components.CorMenuButton> =
  /*@__PURE__*/ createComponent<CorMenuButtonElement, CorMenuButtonEvents, Components.CorMenuButton>({
    tagName: 'cor-menu-button',
    elementClass: CorMenuButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorMenuSelect: 'corMenuSelect' } as CorMenuButtonEvents,
    defineCustomElement: defineCorMenuButton,
  });

export type CorModalEvents = {
  onCorModalClose: EventName<CorModalCustomEvent<void>>;
  onCorModalOpen: EventName<CorModalCustomEvent<void>>;
};

export const CorModal: StencilReactComponent<CorModalElement, CorModalEvents, Components.CorModal> =
  /*@__PURE__*/ createComponent<CorModalElement, CorModalEvents, Components.CorModal>({
    tagName: 'cor-modal',
    elementClass: CorModalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorModalClose: 'corModalClose',
      onCorModalOpen: 'corModalOpen',
    } as CorModalEvents,
    defineCustomElement: defineCorModal,
  });

export type CorPaginationEvents = { onCorPageChange: EventName<CorPaginationCustomEvent<{ page: number }>> };

export const CorPagination: StencilReactComponent<CorPaginationElement, CorPaginationEvents, Components.CorPagination> =
  /*@__PURE__*/ createComponent<CorPaginationElement, CorPaginationEvents, Components.CorPagination>({
    tagName: 'cor-pagination',
    elementClass: CorPaginationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorPageChange: 'corPageChange' } as CorPaginationEvents,
    defineCustomElement: defineCorPagination,
  });

export type CorPaginationGoToEvents = { onCorGoToPage: EventName<CorPaginationGoToCustomEvent<{ page: number }>> };

export const CorPaginationGoTo: StencilReactComponent<
  CorPaginationGoToElement,
  CorPaginationGoToEvents,
  Components.CorPaginationGoTo
> = /*@__PURE__*/ createComponent<CorPaginationGoToElement, CorPaginationGoToEvents, Components.CorPaginationGoTo>({
  tagName: 'cor-pagination-go-to',
  elementClass: CorPaginationGoToElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorGoToPage: 'corGoToPage' } as CorPaginationGoToEvents,
  defineCustomElement: defineCorPaginationGoTo,
});

export type CorPaginationItemEvents = { onCorItemClick: EventName<CorPaginationItemCustomEvent<{ page: number }>> };

export const CorPaginationItem: StencilReactComponent<
  CorPaginationItemElement,
  CorPaginationItemEvents,
  Components.CorPaginationItem
> = /*@__PURE__*/ createComponent<CorPaginationItemElement, CorPaginationItemEvents, Components.CorPaginationItem>({
  tagName: 'cor-pagination-item',
  elementClass: CorPaginationItemElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorItemClick: 'corItemClick' } as CorPaginationItemEvents,
  defineCustomElement: defineCorPaginationItem,
});

export type CorPaginationPageSizeEvents = {
  onCorPageSizeChange: EventName<CorPaginationPageSizeCustomEvent<{ pageSize: number }>>;
};

export const CorPaginationPageSize: StencilReactComponent<
  CorPaginationPageSizeElement,
  CorPaginationPageSizeEvents,
  Components.CorPaginationPageSize
> = /*@__PURE__*/ createComponent<
  CorPaginationPageSizeElement,
  CorPaginationPageSizeEvents,
  Components.CorPaginationPageSize
>({
  tagName: 'cor-pagination-page-size',
  elementClass: CorPaginationPageSizeElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorPageSizeChange: 'corPageSizeChange' } as CorPaginationPageSizeEvents,
  defineCustomElement: defineCorPaginationPageSize,
});

export type CorProgressBarEvents = NonNullable<unknown>;

export const CorProgressBar: StencilReactComponent<
  CorProgressBarElement,
  CorProgressBarEvents,
  Components.CorProgressBar
> = /*@__PURE__*/ createComponent<CorProgressBarElement, CorProgressBarEvents, Components.CorProgressBar>({
  tagName: 'cor-progress-bar',
  elementClass: CorProgressBarElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {} as CorProgressBarEvents,
  defineCustomElement: defineCorProgressBar,
});

export type CorRadioButtonEvents = { onCorChange: EventName<CorRadioButtonCustomEvent<boolean>> };

export const CorRadioButton: StencilReactComponent<
  CorRadioButtonElement,
  CorRadioButtonEvents,
  Components.CorRadioButton
> = /*@__PURE__*/ createComponent<CorRadioButtonElement, CorRadioButtonEvents, Components.CorRadioButton>({
  tagName: 'cor-radio-button',
  elementClass: CorRadioButtonElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorChange: 'corChange' } as CorRadioButtonEvents,
  defineCustomElement: defineCorRadioButton,
});

export type CorRadioButtonGroupEvents = { onCorChange: EventName<CorRadioButtonGroupCustomEvent<string>> };

export const CorRadioButtonGroup: StencilReactComponent<
  CorRadioButtonGroupElement,
  CorRadioButtonGroupEvents,
  Components.CorRadioButtonGroup
> = /*@__PURE__*/ createComponent<
  CorRadioButtonGroupElement,
  CorRadioButtonGroupEvents,
  Components.CorRadioButtonGroup
>({
  tagName: 'cor-radio-button-group',
  elementClass: CorRadioButtonGroupElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorChange: 'corChange' } as CorRadioButtonGroupEvents,
  defineCustomElement: defineCorRadioButtonGroup,
});

export type CorRowEvents = {
  onCorRowClick: EventName<CorRowCustomEvent<{ rowId: string }>>;
  onCorRowSelect: EventName<CorRowCustomEvent<{ rowId: string; selected: boolean }>>;
  onCorRowExpand: EventName<CorRowCustomEvent<{ rowId: string; expanded: boolean }>>;
};

export const CorRow: StencilReactComponent<CorRowElement, CorRowEvents, Components.CorRow> =
  /*@__PURE__*/ createComponent<CorRowElement, CorRowEvents, Components.CorRow>({
    tagName: 'cor-row',
    elementClass: CorRowElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorRowClick: 'corRowClick',
      onCorRowSelect: 'corRowSelect',
      onCorRowExpand: 'corRowExpand',
    } as CorRowEvents,
    defineCustomElement: defineCorRow,
  });

export type CorScrollbarEvents = NonNullable<unknown>;

export const CorScrollbar: StencilReactComponent<CorScrollbarElement, CorScrollbarEvents, Components.CorScrollbar> =
  /*@__PURE__*/ createComponent<CorScrollbarElement, CorScrollbarEvents, Components.CorScrollbar>({
    tagName: 'cor-scrollbar',
    elementClass: CorScrollbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorScrollbarEvents,
    defineCustomElement: defineCorScrollbar,
  });

export type CorSelectEvents = {
  onCorChange: EventName<CorSelectCustomEvent<{ value: string }>>;
  onCorBlur: EventName<CorSelectCustomEvent<void>>;
  onCorFocus: EventName<CorSelectCustomEvent<void>>;
};

export const CorSelect: StencilReactComponent<CorSelectElement, CorSelectEvents, Components.CorSelect> =
  /*@__PURE__*/ createComponent<CorSelectElement, CorSelectEvents, Components.CorSelect>({
    tagName: 'cor-select',
    elementClass: CorSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorChange: 'corChange',
      onCorBlur: 'corBlur',
      onCorFocus: 'corFocus',
    } as CorSelectEvents,
    defineCustomElement: defineCorSelect,
  });

export type CorSelectItemEvents = { onCorSelectionChange: EventName<CorSelectItemCustomEvent<boolean>> };

export const CorSelectItem: StencilReactComponent<CorSelectItemElement, CorSelectItemEvents, Components.CorSelectItem> =
  /*@__PURE__*/ createComponent<CorSelectItemElement, CorSelectItemEvents, Components.CorSelectItem>({
    tagName: 'cor-select-item',
    elementClass: CorSelectItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorSelectionChange: 'corSelectionChange' } as CorSelectItemEvents,
    defineCustomElement: defineCorSelectItem,
  });

export type CorSeparatorEvents = NonNullable<unknown>;

export const CorSeparator: StencilReactComponent<CorSeparatorElement, CorSeparatorEvents, Components.CorSeparator> =
  /*@__PURE__*/ createComponent<CorSeparatorElement, CorSeparatorEvents, Components.CorSeparator>({
    tagName: 'cor-separator',
    elementClass: CorSeparatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorSeparatorEvents,
    defineCustomElement: defineCorSeparator,
  });

export type CorSkeletonEvents = NonNullable<unknown>;

export const CorSkeleton: StencilReactComponent<CorSkeletonElement, CorSkeletonEvents, Components.CorSkeleton> =
  /*@__PURE__*/ createComponent<CorSkeletonElement, CorSkeletonEvents, Components.CorSkeleton>({
    tagName: 'cor-skeleton',
    elementClass: CorSkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorSkeletonEvents,
    defineCustomElement: defineCorSkeleton,
  });

export type CorSlotEvents = NonNullable<unknown>;

export const CorSlot: StencilReactComponent<CorSlotElement, CorSlotEvents, Components.CorSlot> =
  /*@__PURE__*/ createComponent<CorSlotElement, CorSlotEvents, Components.CorSlot>({
    tagName: 'cor-slot',
    elementClass: CorSlotElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorSlotEvents,
    defineCustomElement: defineCorSlot,
  });

export type CorSortingEvents = { onCorSortingChange: EventName<CorSortingCustomEvent<string>> };

export const CorSorting: StencilReactComponent<CorSortingElement, CorSortingEvents, Components.CorSorting> =
  /*@__PURE__*/ createComponent<CorSortingElement, CorSortingEvents, Components.CorSorting>({
    tagName: 'cor-sorting',
    elementClass: CorSortingElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorSortingChange: 'corSortingChange' } as CorSortingEvents,
    defineCustomElement: defineCorSorting,
  });

export type CorSpinnerEvents = NonNullable<unknown>;

export const CorSpinner: StencilReactComponent<CorSpinnerElement, CorSpinnerEvents, Components.CorSpinner> =
  /*@__PURE__*/ createComponent<CorSpinnerElement, CorSpinnerEvents, Components.CorSpinner>({
    tagName: 'cor-spinner',
    elementClass: CorSpinnerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorSpinnerEvents,
    defineCustomElement: defineCorSpinner,
  });

export type CorSystemMessageEvents = NonNullable<unknown>;

export const CorSystemMessage: StencilReactComponent<
  CorSystemMessageElement,
  CorSystemMessageEvents,
  Components.CorSystemMessage
> = /*@__PURE__*/ createComponent<CorSystemMessageElement, CorSystemMessageEvents, Components.CorSystemMessage>({
  tagName: 'cor-system-message',
  elementClass: CorSystemMessageElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {} as CorSystemMessageEvents,
  defineCustomElement: defineCorSystemMessage,
});

export type CorTabButtonEvents = { onCorTabSelect: EventName<CorTabButtonCustomEvent<{ value: string }>> };

export const CorTabButton: StencilReactComponent<CorTabButtonElement, CorTabButtonEvents, Components.CorTabButton> =
  /*@__PURE__*/ createComponent<CorTabButtonElement, CorTabButtonEvents, Components.CorTabButton>({
    tagName: 'cor-tab-button',
    elementClass: CorTabButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorTabSelect: 'corTabSelect' } as CorTabButtonEvents,
    defineCustomElement: defineCorTabButton,
  });

export type CorTableEvents = NonNullable<unknown>;

export const CorTable: StencilReactComponent<CorTableElement, CorTableEvents, Components.CorTable> =
  /*@__PURE__*/ createComponent<CorTableElement, CorTableEvents, Components.CorTable>({
    tagName: 'cor-table',
    elementClass: CorTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorTableEvents,
    defineCustomElement: defineCorTable,
  });

export type CorTableHeaderEvents = NonNullable<unknown>;

export const CorTableHeader: StencilReactComponent<
  CorTableHeaderElement,
  CorTableHeaderEvents,
  Components.CorTableHeader
> = /*@__PURE__*/ createComponent<CorTableHeaderElement, CorTableHeaderEvents, Components.CorTableHeader>({
  tagName: 'cor-table-header',
  elementClass: CorTableHeaderElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {} as CorTableHeaderEvents,
  defineCustomElement: defineCorTableHeader,
});

export type CorTabsEvents = { onCorTabChange: EventName<CorTabsCustomEvent<{ value: string }>> };

export const CorTabs: StencilReactComponent<CorTabsElement, CorTabsEvents, Components.CorTabs> =
  /*@__PURE__*/ createComponent<CorTabsElement, CorTabsEvents, Components.CorTabs>({
    tagName: 'cor-tabs',
    elementClass: CorTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorTabChange: 'corTabChange' } as CorTabsEvents,
    defineCustomElement: defineCorTabs,
  });

export type CorTbodyEvents = NonNullable<unknown>;

export const CorTbody: StencilReactComponent<CorTbodyElement, CorTbodyEvents, Components.CorTbody> =
  /*@__PURE__*/ createComponent<CorTbodyElement, CorTbodyEvents, Components.CorTbody>({
    tagName: 'cor-tbody',
    elementClass: CorTbodyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorTbodyEvents,
    defineCustomElement: defineCorTbody,
  });

export type CorTextareaEvents = {
  onCorInput: EventName<CorTextareaCustomEvent<string>>;
  onCorBlur: EventName<CorTextareaCustomEvent<void>>;
  onCorFocus: EventName<CorTextareaCustomEvent<void>>;
};

export const CorTextarea: StencilReactComponent<CorTextareaElement, CorTextareaEvents, Components.CorTextarea> =
  /*@__PURE__*/ createComponent<CorTextareaElement, CorTextareaEvents, Components.CorTextarea>({
    tagName: 'cor-textarea',
    elementClass: CorTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorInput: 'corInput',
      onCorBlur: 'corBlur',
      onCorFocus: 'corFocus',
    } as CorTextareaEvents,
    defineCustomElement: defineCorTextarea,
  });

export type CorTfootEvents = NonNullable<unknown>;

export const CorTfoot: StencilReactComponent<CorTfootElement, CorTfootEvents, Components.CorTfoot> =
  /*@__PURE__*/ createComponent<CorTfootElement, CorTfootEvents, Components.CorTfoot>({
    tagName: 'cor-tfoot',
    elementClass: CorTfootElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorTfootEvents,
    defineCustomElement: defineCorTfoot,
  });

export type CorTheadEvents = { onCorSelectAll: EventName<CorTheadCustomEvent<{ selected: boolean }>> };

export const CorThead: StencilReactComponent<CorTheadElement, CorTheadEvents, Components.CorThead> =
  /*@__PURE__*/ createComponent<CorTheadElement, CorTheadEvents, Components.CorThead>({
    tagName: 'cor-thead',
    elementClass: CorTheadElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorSelectAll: 'corSelectAll' } as CorTheadEvents,
    defineCustomElement: defineCorThead,
  });

export type CorTimelineEvents = {
  onCorTimelineChange: EventName<CorTimelineCustomEvent<CorTimelineChangeEvent>>;
  onCorTimelineScrollEnd: EventName<CorTimelineCustomEvent<CorTimelineScrollEndEvent>>;
};

export const CorTimeline: StencilReactComponent<CorTimelineElement, CorTimelineEvents, Components.CorTimeline> =
  /*@__PURE__*/ createComponent<CorTimelineElement, CorTimelineEvents, Components.CorTimeline>({
    tagName: 'cor-timeline',
    elementClass: CorTimelineElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorTimelineChange: 'corTimelineChange',
      onCorTimelineScrollEnd: 'corTimelineScrollEnd',
    } as CorTimelineEvents,
    defineCustomElement: defineCorTimeline,
  });

export type CorToastNotificationEvents = { onCorDismiss: EventName<CorToastNotificationCustomEvent<void>> };

export const CorToastNotification: StencilReactComponent<
  CorToastNotificationElement,
  CorToastNotificationEvents,
  Components.CorToastNotification
> = /*@__PURE__*/ createComponent<
  CorToastNotificationElement,
  CorToastNotificationEvents,
  Components.CorToastNotification
>({
  tagName: 'cor-toast-notification',
  elementClass: CorToastNotificationElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorDismiss: 'corDismiss' } as CorToastNotificationEvents,
  defineCustomElement: defineCorToastNotification,
});

export type CorToggleEvents = { onCorChange: EventName<CorToggleCustomEvent<boolean>> };

export const CorToggle: StencilReactComponent<CorToggleElement, CorToggleEvents, Components.CorToggle> =
  /*@__PURE__*/ createComponent<CorToggleElement, CorToggleEvents, Components.CorToggle>({
    tagName: 'cor-toggle',
    elementClass: CorToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCorChange: 'corChange' } as CorToggleEvents,
    defineCustomElement: defineCorToggle,
  });

export type CorTooltipEvents = {
  onCorTooltipShow: EventName<CorTooltipCustomEvent<void>>;
  onCorTooltipHide: EventName<CorTooltipCustomEvent<void>>;
};

export const CorTooltip: StencilReactComponent<CorTooltipElement, CorTooltipEvents, Components.CorTooltip> =
  /*@__PURE__*/ createComponent<CorTooltipElement, CorTooltipEvents, Components.CorTooltip>({
    tagName: 'cor-tooltip',
    elementClass: CorTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorTooltipShow: 'corTooltipShow',
      onCorTooltipHide: 'corTooltipHide',
    } as CorTooltipEvents,
    defineCustomElement: defineCorTooltip,
  });

export type CorTypographyEvents = NonNullable<unknown>;

export const CorTypography: StencilReactComponent<CorTypographyElement, CorTypographyEvents, Components.CorTypography> =
  /*@__PURE__*/ createComponent<CorTypographyElement, CorTypographyEvents, Components.CorTypography>({
    tagName: 'cor-typography',
    elementClass: CorTypographyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CorTypographyEvents,
    defineCustomElement: defineCorTypography,
  });

export type CorUploadAreaEvents = {
  onCorFilesSelected: EventName<CorUploadAreaCustomEvent<{ files: CorUploadFile[] }>>;
  onCorFilesRejected: EventName<CorUploadAreaCustomEvent<{ files: CorRejectedFile[] }>>;
  onCorBrowseClick: EventName<CorUploadAreaCustomEvent<void>>;
  onCorCancelClick: EventName<CorUploadAreaCustomEvent<void>>;
  onCorDragEnter: EventName<CorUploadAreaCustomEvent<void>>;
  onCorDragLeave: EventName<CorUploadAreaCustomEvent<void>>;
  onCorDrop: EventName<CorUploadAreaCustomEvent<{ files: FileList }>>;
};

export const CorUploadArea: StencilReactComponent<CorUploadAreaElement, CorUploadAreaEvents, Components.CorUploadArea> =
  /*@__PURE__*/ createComponent<CorUploadAreaElement, CorUploadAreaEvents, Components.CorUploadArea>({
    tagName: 'cor-upload-area',
    elementClass: CorUploadAreaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onCorFilesSelected: 'corFilesSelected',
      onCorFilesRejected: 'corFilesRejected',
      onCorBrowseClick: 'corBrowseClick',
      onCorCancelClick: 'corCancelClick',
      onCorDragEnter: 'corDragEnter',
      onCorDragLeave: 'corDragLeave',
      onCorDrop: 'corDrop',
    } as CorUploadAreaEvents,
    defineCustomElement: defineCorUploadArea,
  });

export type CorUploadFileItemEvents = {
  onCorRemoveFile: EventName<CorUploadFileItemCustomEvent<{ fileName: string }>>;
};

export const CorUploadFileItem: StencilReactComponent<
  CorUploadFileItemElement,
  CorUploadFileItemEvents,
  Components.CorUploadFileItem
> = /*@__PURE__*/ createComponent<CorUploadFileItemElement, CorUploadFileItemEvents, Components.CorUploadFileItem>({
  tagName: 'cor-upload-file-item',
  elementClass: CorUploadFileItemElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onCorRemoveFile: 'corRemoveFile' } as CorUploadFileItemEvents,
  defineCustomElement: defineCorUploadFileItem,
});
