/**
 * Resolves the canonical file layout of a `mud-*` component.
 *
 * Project convention (from `.claude/skills/audit-component/SKILL.md`):
 *   src/components/mud-<name>/
 *     ├── mud-<name>.tsx                 REQUIRED
 *     ├── mud-<name>.css                 REQUIRED
 *     ├── mud-<name>.stories.ts          REQUIRED
 *     ├── mud-<name>.types.ts            OPTIONAL
 *     ├── mud-<name>.enums.ts            OPTIONAL
 *     ├── mud-<name>.constants.ts        OPTIONAL
 *     ├── test/mud-<name>.spec.tsx       REQUIRED (unit)
 *     ├── test/mud-<name>.e2e.ts         OPTIONAL
 *     └── readme.md                      REQUIRED (auto-generated by Stencil)
 *
 * Tokens (3-tier hierarchy):
 *   tokens/core/components/<bare-name>.tokens.json  (where bare-name == mud-X without the mud- prefix)
 *
 * A component may live under src/components/ OR src/hidden/ (work-in-progress
 * area). This module checks both locations and reports which one matched.
 *
 * All functions are pure and synchronous — they only return paths, never read files.
 */
import path from 'node:path';
import { readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

const COMPONENTS_ROOT = path.join(REPO_ROOT, 'src', 'components');
const HIDDEN_ROOT = path.join(REPO_ROOT, 'src', 'hidden');
const TOKENS_COMPONENTS_ROOT = path.join(REPO_ROOT, 'tokens', 'core', 'components');

/**
 * Normalize a user-provided component name. Accepts:
 *   - "mud-button"        → "mud-button"
 *   - "button"            → "mud-button"
 *   - "@mud-button"       → "mud-button"        (Claude Code @-prefix convention)
 *   - "mud-button/"       → "mud-button"
 *
 * Returns null if the input doesn't look like a valid component name.
 */
export function normalizeComponentName(input) {
  if (typeof input !== 'string') return null;
  let name = input
    .trim()
    .replace(/^@/, '')
    .replace(/[/\\]+$/, '');
  if (!name) return null;
  if (!name.startsWith('mud-')) name = `mud-${name}`;
  if (!/^mud-[a-z0-9-]+$/.test(name)) return null;
  return name;
}

/** "mud-button" → "button"  (used for tokens/core/components/<bare>.tokens.json) */
export function bareName(componentName) {
  return componentName.replace(/^mud-/, '');
}

/**
 * Resolve all expected paths for a component.
 *
 * Returns an object with a `root` (the folder that actually exists) and a map
 * of file kind → absolute path. A path is returned even if the file doesn't
 * exist yet — callers use `paths.exists.<kind>` to check.
 *
 * If neither `src/components/<name>/` nor `src/hidden/<name>/` exists, returns
 * `{ found: false, ... }` so the caller can produce a clean "not found" error.
 */
export function resolveComponentPaths(componentName) {
  const name = normalizeComponentName(componentName);
  if (!name) {
    return { found: false, reason: 'invalid-name', input: componentName };
  }

  const bare = bareName(name);
  const candidates = [
    { location: 'components', root: path.join(COMPONENTS_ROOT, name) },
    { location: 'hidden', root: path.join(HIDDEN_ROOT, name) },
  ];

  let matched = null;
  for (const c of candidates) {
    if (isDirSafe(c.root)) {
      matched = c;
      break;
    }
  }

  if (!matched) {
    return {
      found: false,
      reason: 'not-found',
      name,
      bare,
      searched: candidates.map(c => c.root),
    };
  }

  const root = matched.root;
  const paths = {
    tsx: path.join(root, `${name}.tsx`),
    css: path.join(root, `${name}.css`),
    stories: path.join(root, `${name}.stories.ts`),
    types: path.join(root, `${name}.types.ts`),
    enums: path.join(root, `${name}.enums.ts`),
    constants: path.join(root, `${name}.constants.ts`),
    providers: path.join(root, `${name}.providers.ts`),
    spec: path.join(root, 'test', `${name}.spec.tsx`),
    e2e: path.join(root, 'test', `${name}.e2e.ts`),
    readme: path.join(root, 'readme.md'),
    tokens: path.join(TOKENS_COMPONENTS_ROOT, `${bare}.tokens.json`),
  };

  const exists = {};
  for (const [kind, p] of Object.entries(paths)) {
    exists[kind] = isFileSafe(p);
  }

  return {
    found: true,
    name,
    bare,
    location: matched.location, // 'components' | 'hidden'
    root,
    paths,
    exists,
  };
}

/**
 * List all `mud-*` components in src/components/ and src/hidden/. Returns sorted
 * objects with `{ name, location, root }`. Used by `--all` mode in audit scripts.
 */
export function listAllComponents() {
  const out = [];
  for (const [location, base] of [
    ['components', COMPONENTS_ROOT],
    ['hidden', HIDDEN_ROOT],
  ]) {
    if (!isDirSafe(base)) continue;
    for (const entry of readDirSafe(base)) {
      if (!entry.startsWith('mud-')) continue;
      const root = path.join(base, entry);
      if (isDirSafe(root)) out.push({ name: entry, location, root });
    }
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

/** Convert an absolute path to a repo-relative one with forward slashes (for stable output). */
export function relativeToRepo(absPath) {
  return path.relative(REPO_ROOT, absPath).split(path.sep).join('/');
}

// ─── internal ────────────────────────────────────────────────────────────────

function isDirSafe(p) {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

function isFileSafe(p) {
  try {
    return statSync(p).isFile();
  } catch {
    return false;
  }
}

function readDirSafe(p) {
  try {
    return readdirSync(p);
  } catch {
    return [];
  }
}
