// Every generated Vue wrapper produced by @stencil/vue-output-target. The proxies are
// generated by `yarn build` at the repo root and are never committed.
export * from './components/stencil-generated/components.js';

// The hand-written wrappers replace the generated ones of the same name: an explicit export
// takes precedence over `export *`. See `scripts/adapters/form-models.ts` (`vueBindingKind`).
export { MudNumericInput } from './wrappers/numeric-input.js';
export { MudPhoneInput } from './wrappers/phone-input.js';
