import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

// Contract for `.storybook/custom-elements.json`, the manifest every Storybook API
// table is built from (`.storybook/preview.js`). It is generated by the Stencil build,
// so run `yarn build` (or any `stencil build`) before this spec.
//
// The reference it is checked against is each component's `readme.md`: Stencil's
// `docs-readme` target writes those from the same `@part` tags and `@Event()`
// decorators, and issue #18 was precisely a manifest that disagreed with them.

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const MANIFEST_PATH = path.join(ROOT, '.storybook/custom-elements.json');

function loadManifest() {
  assert.ok(fs.existsSync(MANIFEST_PATH), `${MANIFEST_PATH} is missing — run \`yarn build\` first`);
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
  // A checkout that last built before this change still holds the old generator's
  // `version: "experimental"` manifest; name the fix rather than failing on its shape.
  assert.notEqual(manifest.version, 'experimental', 'stale pre-Stencil manifest on disk — run `yarn build`');
  return manifest;
}

function declarations(manifest) {
  return (manifest.modules ?? []).flatMap(module =>
    (module.declarations ?? []).filter(d => d.customElement).map(d => ({ ...d, modulePath: module.path })),
  );
}

// Tag names from Stencil's own generated typings, not from parsing component source.
function tagsFromTypings() {
  const typings = fs.readFileSync(path.join(ROOT, 'src/components.d.ts'), 'utf8');
  const map = typings.slice(typings.indexOf('interface HTMLElementTagNameMap'));
  return new Set([...map.slice(0, map.indexOf('}')).matchAll(/"(mud-[a-z0-9-]+)":/g)].map(m => m[1]));
}

// A directory holding several components has one `readme.md`, which the last component
// Stencil documents overwrites; its `# <tag>` title says whose it is. Only a readme
// titled with this declaration's tag is a reference for it.
function readmeFor(declaration) {
  const readmePath = path.join(ROOT, path.dirname(declaration.modulePath), 'readme.md');
  if (!fs.existsSync(readmePath)) return null;
  const readme = fs.readFileSync(readmePath, 'utf8');
  return readme.startsWith(`# ${declaration.tagName}\n`) ? readme : null;
}

function readmeSection(readme, heading) {
  const start = readme.indexOf(`\n## ${heading}\n`);
  if (start === -1) return null;
  const rest = readme.slice(start + heading.length + 5);
  const end = rest.indexOf('\n## ');
  return end === -1 ? rest : rest.slice(0, end);
}

// Names documented in a Stencil readme section: the first column of the Events and
// Shadow Parts tables (after header and separator rows; parts are quoted), or the
// `### \`name(...)\`` headings of the Methods section.
function documentedNames(section, heading) {
  if (heading === 'Methods') return [...section.matchAll(/^### `([A-Za-z0-9_]+)\(/gm)].map(m => m[1]);
  return section
    .split('\n')
    .filter(line => line.startsWith('|'))
    .slice(2)
    .map(line =>
      line
        .split('|')[1]
        .trim()
        .replace(/^`"?|"?`$/g, ''),
    );
}

describe('.storybook/custom-elements.json', () => {
  it('uses the Custom Elements Manifest 2.x shape Storybook reads through modules[]', () => {
    const manifest = loadManifest();
    assert.match(String(manifest.schemaVersion), /^2\./);
    assert.ok(Array.isArray(manifest.modules));
  });

  it('declares exactly the tags Stencil compiled', () => {
    const manifestTags = new Set(declarations(loadManifest()).map(d => d.tagName));
    assert.deepEqual([...manifestTags].sort(), [...tagsFromTypings()].sort());
  });

  for (const [heading, field] of [
    ['Events', 'events'],
    ['Shadow Parts', 'cssParts'],
    ['Methods', 'members'],
    ['Properties', 'members'],
    ['Slots', 'slots'],
  ]) {
    it(`lists every ${heading.toLowerCase()} entry the component readme documents`, () => {
      const missing = [];
      let compared = 0;
      for (const declaration of declarations(loadManifest())) {
        const readme = readmeFor(declaration);
        const section = readme && readmeSection(readme, heading);
        if (!section) continue;
        const listed = new Set((declaration[field] ?? []).map(item => item.name));
        for (const name of documentedNames(section, heading)) {
          compared++;
          if (!listed.has(name)) missing.push(`${declaration.tagName}: ${name}`);
        }
      }
      assert.ok(compared > 0, `no readme documented any ${heading.toLowerCase()} — the reference parser found nothing`);
      assert.deepEqual(missing, []);
    });
  }

  it('gives each property its attribute name', () => {
    const button = declarations(loadManifest()).find(d => d.tagName === 'mud-button');
    const fullWidth = button.members.find(m => m.kind === 'field' && m.name === 'fullWidth');
    assert.equal(fullWidth?.attribute, 'full-width');
  });
});
