{{- range (.Values.serviceAccount).roleBinding -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ printf "%s%s" .kind "Binding" }}
metadata:
  name: {{ printf "%s-%s" (include "app.fullname" $) .name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ default (include "app.fullname" $) $.Values.serviceAccount.name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ required "roleBinding.kind is required!" .kind }}
  name: {{ required "roleBinding.role is required!" .role }}
---
{{- end }}