{{- range $secretKey, $secret := .Values.secret -}}
{{- if hasKey $secret "enabled" | ternary $secret.enabled true -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "app.fullname" $) $secretKey }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
{{- with $secret.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
data:
{{- range $key, $value := $secret.strings }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- range $key, $value := $secret.templates }}
  {{ $key }}: {{ tpl ($.Files.Get $value) $ | b64enc }}
{{- end }}
---
{{- end }}
{{- end }}