{{- range $workloadKey, $workload := mustMerge (dict) (default (dict) .Values.deployment) (default (dict) .Values.statefulSet) -}}
{{- if ne "None" (default "ClusterIP" ($workload.service).type) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "app.fullname" $) $workloadKey }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- toYaml $workload.labels | nindent 4 }}
{{- with ($workload.service).annotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  selector:
    {{- include "app.selector" $ | nindent 4 }}
    {{- toYaml $workload.labels | nindent 4 }}
{{- with ($workload.service).type }}
  type: {{ . }}
{{- end }}
{{- with ($workload.service).externalIPs }}
  externalIPs: {{ toYaml . | nindent 2 }}
{{- end }}
{{- with ($workload.service).loadBalancerIP }}
  loadBalancerIP: {{ . }}
{{- end }}
{{- with ($workload.service).externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
{{- end }}
{{- if ($workload.service).ports }}
  ports: {{ toYaml $workload.service.ports | nindent 2 }}
{{- else if eq "aspnet" $workload.portsPreset }}
  ports:
  - name: http
    port: 8080
    targetPort: http
{{- end }}
---
{{- end }}
{{- end }}