/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SpinnerSize, SpinnerVariant } from "./components/cor-spinner/cor-spinner.types";
export { SpinnerSize, SpinnerVariant } from "./components/cor-spinner/cor-spinner.types";
export namespace Components {
    /**
     * Spinner — animated circular loading indicator.
     * Pattern B (atom-visual): renders a CSS-only rotating arc.
     * No slots, no events, no interactivity.
     * @element cor-spinner
     */
    interface CorSpinner {
        /**
          * Accessible label for screen readers.
          * @default 'Loading'
         */
        "label": string;
        /**
          * Visual size rung.
          * @default 'md'
         */
        "size": SpinnerSize;
        /**
          * Color treatment.
          * @default 'brand'
         */
        "variant": SpinnerVariant;
    }
}
declare global {
    /**
     * Spinner — animated circular loading indicator.
     * Pattern B (atom-visual): renders a CSS-only rotating arc.
     * No slots, no events, no interactivity.
     * @element cor-spinner
     */
    interface HTMLCorSpinnerElement extends Components.CorSpinner, HTMLStencilElement {
    }
    var HTMLCorSpinnerElement: {
        prototype: HTMLCorSpinnerElement;
        new (): HTMLCorSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "cor-spinner": HTMLCorSpinnerElement;
    }
}
declare namespace LocalJSX {
    /**
     * Spinner — animated circular loading indicator.
     * Pattern B (atom-visual): renders a CSS-only rotating arc.
     * No slots, no events, no interactivity.
     * @element cor-spinner
     */
    interface CorSpinner {
        /**
          * Accessible label for screen readers.
          * @default 'Loading'
         */
        "label"?: string;
        /**
          * Visual size rung.
          * @default 'md'
         */
        "size"?: SpinnerSize;
        /**
          * Color treatment.
          * @default 'brand'
         */
        "variant"?: SpinnerVariant;
    }

    interface CorSpinnerAttributes {
        "size": SpinnerSize;
        "variant": SpinnerVariant;
        "label": string;
    }

    interface IntrinsicElements {
        "cor-spinner": Omit<CorSpinner, keyof CorSpinnerAttributes> & { [K in keyof CorSpinner & keyof CorSpinnerAttributes]?: CorSpinner[K] } & { [K in keyof CorSpinner & keyof CorSpinnerAttributes as `attr:${K}`]?: CorSpinnerAttributes[K] } & { [K in keyof CorSpinner & keyof CorSpinnerAttributes as `prop:${K}`]?: CorSpinner[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Spinner — animated circular loading indicator.
             * Pattern B (atom-visual): renders a CSS-only rotating arc.
             * No slots, no events, no interactivity.
             * @element cor-spinner
             */
            "cor-spinner": LocalJSX.IntrinsicElements["cor-spinner"] & JSXBase.HTMLAttributes<HTMLCorSpinnerElement>;
        }
    }
}
