/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconSize } from "./components/cor-icon/cor-icon.types";
import { SpinnerSize, SpinnerVariant } from "./components/cor-spinner/cor-spinner.types";
export { IconSize } from "./components/cor-icon/cor-icon.types";
export { SpinnerSize, SpinnerVariant } from "./components/cor-spinner/cor-spinner.types";
export namespace Components {
    /**
     * Icon — renders an inline SVG fetched on-demand from per-size asset files.
     * Names follow the Material Symbols convention: append `-filled` to the base name
     * to request the filled variant (e.g. `check` outlined vs `check-filled`).
     * When the exact `size`/`name` combination is missing from the manifest, the
     * provider falls back to the closest larger size (preferred) and then to the
     * largest smaller size before giving up.
     * @element cor-icon
     */
    interface CorIcon {
        /**
          * Accessible label. When provided, the icon is announced; when omitted it is decorative.
         */
        "ariaLabel"?: string;
        /**
          * Color token suffix (mapped to `--color-{value}`), or `currentColor` to inherit text color.
          * @default 'icon-base-secondary'
         */
        "color": string;
        /**
          * Reflects to `[disabled]` and visually disables the icon.
          * @default false
         */
        "disabled": boolean;
        /**
          * Enables interactive treatment (cursor, hover, focus ring, keyboard activation).
          * @default false
         */
        "interactive": boolean;
        /**
          * Icon identifier (kebab-case). Suffix `-filled` selects the filled variant.
          * @default 'check'
         */
        "name": string;
        /**
          * Pixel size, aligned with Figma Foundations: 12 / 16 / 20 / 24.
          * @default 16
         */
        "size": IconSize;
    }
    /**
     * Spinner — animated circular loading indicator.
     * Pattern B (atom-visual): renders a CSS-only rotating arc.
     * No slots, no events, no interactivity.
     * @element cor-spinner
     */
    interface CorSpinner {
        /**
          * Accessible label for screen readers.
          * @default 'Loading'
         */
        "label": string;
        /**
          * Visual size rung.
          * @default 'md'
         */
        "size": SpinnerSize;
        /**
          * Color treatment.
          * @default 'brand'
         */
        "variant": SpinnerVariant;
    }
}
declare global {
    /**
     * Icon — renders an inline SVG fetched on-demand from per-size asset files.
     * Names follow the Material Symbols convention: append `-filled` to the base name
     * to request the filled variant (e.g. `check` outlined vs `check-filled`).
     * When the exact `size`/`name` combination is missing from the manifest, the
     * provider falls back to the closest larger size (preferred) and then to the
     * largest smaller size before giving up.
     * @element cor-icon
     */
    interface HTMLCorIconElement extends Components.CorIcon, HTMLStencilElement {
    }
    var HTMLCorIconElement: {
        prototype: HTMLCorIconElement;
        new (): HTMLCorIconElement;
    };
    /**
     * Spinner — animated circular loading indicator.
     * Pattern B (atom-visual): renders a CSS-only rotating arc.
     * No slots, no events, no interactivity.
     * @element cor-spinner
     */
    interface HTMLCorSpinnerElement extends Components.CorSpinner, HTMLStencilElement {
    }
    var HTMLCorSpinnerElement: {
        prototype: HTMLCorSpinnerElement;
        new (): HTMLCorSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "cor-icon": HTMLCorIconElement;
        "cor-spinner": HTMLCorSpinnerElement;
    }
}
declare namespace LocalJSX {
    /**
     * Icon — renders an inline SVG fetched on-demand from per-size asset files.
     * Names follow the Material Symbols convention: append `-filled` to the base name
     * to request the filled variant (e.g. `check` outlined vs `check-filled`).
     * When the exact `size`/`name` combination is missing from the manifest, the
     * provider falls back to the closest larger size (preferred) and then to the
     * largest smaller size before giving up.
     * @element cor-icon
     */
    interface CorIcon {
        /**
          * Accessible label. When provided, the icon is announced; when omitted it is decorative.
         */
        "ariaLabel"?: string;
        /**
          * Color token suffix (mapped to `--color-{value}`), or `currentColor` to inherit text color.
          * @default 'icon-base-secondary'
         */
        "color"?: string;
        /**
          * Reflects to `[disabled]` and visually disables the icon.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Enables interactive treatment (cursor, hover, focus ring, keyboard activation).
          * @default false
         */
        "interactive"?: boolean;
        /**
          * Icon identifier (kebab-case). Suffix `-filled` selects the filled variant.
          * @default 'check'
         */
        "name"?: string;
        /**
          * Pixel size, aligned with Figma Foundations: 12 / 16 / 20 / 24.
          * @default 16
         */
        "size"?: IconSize;
    }
    /**
     * Spinner — animated circular loading indicator.
     * Pattern B (atom-visual): renders a CSS-only rotating arc.
     * No slots, no events, no interactivity.
     * @element cor-spinner
     */
    interface CorSpinner {
        /**
          * Accessible label for screen readers.
          * @default 'Loading'
         */
        "label"?: string;
        /**
          * Visual size rung.
          * @default 'md'
         */
        "size"?: SpinnerSize;
        /**
          * Color treatment.
          * @default 'brand'
         */
        "variant"?: SpinnerVariant;
    }

    interface CorIconAttributes {
        "name": string;
        "size": IconSize;
        "color": string;
        "interactive": boolean;
        "disabled": boolean;
        "ariaLabel": string;
    }
    interface CorSpinnerAttributes {
        "size": SpinnerSize;
        "variant": SpinnerVariant;
        "label": string;
    }

    interface IntrinsicElements {
        "cor-icon": Omit<CorIcon, keyof CorIconAttributes> & { [K in keyof CorIcon & keyof CorIconAttributes]?: CorIcon[K] } & { [K in keyof CorIcon & keyof CorIconAttributes as `attr:${K}`]?: CorIconAttributes[K] } & { [K in keyof CorIcon & keyof CorIconAttributes as `prop:${K}`]?: CorIcon[K] };
        "cor-spinner": Omit<CorSpinner, keyof CorSpinnerAttributes> & { [K in keyof CorSpinner & keyof CorSpinnerAttributes]?: CorSpinner[K] } & { [K in keyof CorSpinner & keyof CorSpinnerAttributes as `attr:${K}`]?: CorSpinnerAttributes[K] } & { [K in keyof CorSpinner & keyof CorSpinnerAttributes as `prop:${K}`]?: CorSpinner[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Icon — renders an inline SVG fetched on-demand from per-size asset files.
             * Names follow the Material Symbols convention: append `-filled` to the base name
             * to request the filled variant (e.g. `check` outlined vs `check-filled`).
             * When the exact `size`/`name` combination is missing from the manifest, the
             * provider falls back to the closest larger size (preferred) and then to the
             * largest smaller size before giving up.
             * @element cor-icon
             */
            "cor-icon": LocalJSX.IntrinsicElements["cor-icon"] & JSXBase.HTMLAttributes<HTMLCorIconElement>;
            /**
             * Spinner — animated circular loading indicator.
             * Pattern B (atom-visual): renders a CSS-only rotating arc.
             * No slots, no events, no interactivity.
             * @element cor-spinner
             */
            "cor-spinner": LocalJSX.IntrinsicElements["cor-spinner"] & JSXBase.HTMLAttributes<HTMLCorSpinnerElement>;
        }
    }
}
